name: input_decorator
description: InputDecoration that has ErrorBuilder
version: 0.0.1
homepage: https://github.com/MohiuddinM/input_decorator

environment:
  sdk: ^3.0.0
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
